### ISSUE TITLE
can not find xtm1638.h

### ISSUE THREAD

**Issue by MasterSch** [ErwinHaantjes/xtm1638#1]
hi,
i am new on GitHub. I downloaded the zip file but i can not find a xtm1638.h file in the zip file.
maybe I do something wrong?

wbr
Günter

**Comment by codebeat-nl** [comment]
Sorry for the late reply. Something was wrong (not uploaded). Now the source code is there with some updates. I have updated also the readme file. See also the examples what you can do with it. Have fun.
codebeat.
