### ISSUE TITLE
Possible modification to setChars...

### ISSUE THREAD

**Issue by amordicus** [ErwinHaantjes/xtm1638#2]
While using setChars I've notice that "." is displayed as three horizontal bars. For example setChars("32.1") displays 32(3 horizontal bars)1 instead of 32.1
It would be nice if the dot was displayed as a dot on the same segment digit 2 in my example.

Such a fix would make displaying decimal number very easy, or do you already have a way to do this?

P.S. this is a great library and very impressive as far as speed is concerned. And the examples are A++.

**Comment by codebeat-nl** [comment]
Hi, thanks for trying and compliments!

The '.' character does not exist because the dot is a part of a digit like you just pointed out. Another thing, you showed the number as characters, the setChars function treat the numbers as characters and not as a number. What you have, is actually a float. I need to write a function for it to support this. 

However, as temporarily workaround I came up with this idea (not the fastest solution anyway):

```
void printFloat( float fValue )
{
  String sValue = String( fValue, 1 );    // Get float with one decimal
  int8_t iDot      = sValue.indexOf(".");  // Find the dot in the string
   if( iDot >= 0 )
   {
      // Set a fixed dot on position
      ledandkey.setDots( 1 <<  (iDot-1) );
       // Remove dot from string
      sValue.remove(iDot, 1);  
   }
    
   // Show value as string 
   ledandkey.setChars( sValue.c_str() );
    
    // Reset the dots
   ledandkey.setDots( 0 );
}

```
Example how to use:
`printFloat( 32.1 );
`
I did not test it but should work. Hopes it helps.

**Comment by amordicus** [comment]
Thanks

I understand that 32.1 is a float but in my example I passed it as a string “32.1” and it should have worked (see my next comment about XTM_MEM_ALLOC_TYPE). I know it would deviate from your definition of a char but being able to move the dot at the expected place on the display would be nice. Or as you said you could write a new function, something like setCharsWithDotInSegment.  In my case I just wanted to display temperature with decimal value something like "String myString = String(celsius) + "^C” ;"

About your code:
Yes that should work except for passing a String to setChars which needs a char*.  Also the function should not limit one decimal, but I’m sure you’ll figure all the details out when you have time.

What I have temporally done is adding    (uint8_t)'.', XTM_DOT, to XTM_MEM_ALLOC_TYPE in your xtm1638.h file, as you said this uses a full segment but I can live with that for now.  You may want to add XTM_DOT to your code since “.” is a possible character! A bit of a waste but someone may need it!? Or just put it where it belongs.

XTM_MEM_ALLOC_TYPE const uint8_t XTM_DIGITS[] =
{
.
.
.
   (uint8_t)'?', XTM_QUESTION_MARK,
   (uint8_t)'.', XTM_DOT,
   0x00
};

Thanks for your help I will use your code if I’m in need of an extras segment!
